name: lucy_editor
description: "Lucy Editor is improved performance about re-editor"
version: 1.0.4
homepage: http://www.edencrew.kr
repository: https://github.com/ellie-k-nam/lucy_editor

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  collection: ^1.17.1
  http: ^1.2.1
  equatable: ^2.0.3
  linked_scroll_controller: ^0.2.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  path: ^1.8.2
