library re_editor;

import 'dart:async';
import 'dart:io';
import 'dart:isolate';
import 'dart:math';
import 'dart:ui' as ui;
import 'dart:collection';

import 'package:collection/collection.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:highlight/highlight.dart' as hi;
import 'package:highlight/languages/javascript.dart' as js;
import 'package:highlight/languages/json.dart' as json;
import 'package:linked_scroll_controller/linked_scroll_controller.dart';
import 'package:lucy_editor/languages/json.dart';
import 'package:lucy_editor/src/search/settings_controller.dart';

import '../jsparser.dart';
import '../languages/javascript.dart';
import '../parsejs/ast.dart';
import './re_highlight.dart';
import 'analyzer/models/analysis_result.dart';
import 'analyzer/models/error.dart';

part '_code_editable.dart';
part '_code_extensions.dart';
part '_code_field.dart';
part '_code_find.dart';
part '_code_formatter.dart';
part '_code_highlight.dart';
part '_code_indicator.dart';
part '_code_input.dart';
part '_code_line.dart';
part '_code_lines.dart';
part '_code_paragraph.dart';
part '_code_scroll.dart';
part '_code_selection.dart';
part '_code_shortcuts.dart';
part '_isolate.dart';
part 'code_autocomplete.dart';
part 'code_chunk.dart';
part 'code_editor.dart';
part 'code_find.dart';
part 'code_formatter.dart';
part 'code_indicator.dart';
part 'code_line.dart';
part 'code_lines.dart';
part 'code_paragraph.dart';
part 'code_shortcuts.dart';
part 'code_scroll.dart';
part 'code_theme.dart';
part 'code_toolbar.dart';
part 'debug/_trace.dart';