name: re_highlight
description: Re-Highlight is a powerful text syntax highlighting library.
version: 0.0.3
homepage: https://reqable.com
repository: https://github.com/reqable/re-highlight

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0